"""
backend/tests/test_agent_summary_fallback.py

Tests the fallback, exception handling, and timeout behavior of the
LLM-based natural language summary generator.
"""

from unittest.mock import MagicMock, patch

import requests

from backend.agent.pipeline import run_investigation_pipeline
from backend.agent.summary import generate_llm_summary


@patch("requests.post")
def test_llm_summary_success_mock(mock_post):
    """Verifies that a successful LLM API call returns the parsed summary text."""
    # Set up mock response
    mock_response = MagicMock()
    mock_response.status_code = 200
    mock_response.json.return_ok = True
    mock_response.json.return_value = {
        "choices": [
            {
                "message": {
                    "content": "This is a rich natural language summary generated by the mocked LLM."
                }
            }
        ]
    }
    mock_post.return_value = mock_response

    # Force API key in environment to trigger LLM path
    with patch.dict(
        "os.environ",
        {"OPENAI_API_KEY": "fake-key", "OPENAI_API_BASE": "https://api.openai.com/v1"},
    ):
        summary, llm_error = generate_llm_summary(
            latitude=28.566,
            longitude=77.186,
            current_aqi=312.0,
            primary_cause="traffic",
            confidence=80.0,
            forecast_value=290.0,
            forecast_lower=250.0,
            forecast_upper=320.0,
            selected_interventions=[],
            total_aqi_reduction=0.0,
            projected_aqi=312.0,
            health_benefit=0.0,
            enable_llm=True,
        )

        assert (
            summary
            == "This is a rich natural language summary generated by the mocked LLM."
        )
        assert llm_error is False
        # Confirm post was called with timeout parameter
        mock_post.assert_called_once()
        kwargs = mock_post.call_args[1]
        assert kwargs.get("timeout") == 1.5


@patch("requests.post")
def test_llm_summary_timeout_mock(mock_post):
    """Verifies that a simulated timeout results in a fallback report and llm_error=True."""
    mock_post.side_effect = requests.exceptions.Timeout("Connection timed out")

    with patch.dict("os.environ", {"OPENAI_API_KEY": "fake-key"}):
        summary, llm_error = generate_llm_summary(
            latitude=28.566,
            longitude=77.186,
            current_aqi=312.0,
            primary_cause="traffic",
            confidence=80.0,
            forecast_value=290.0,
            forecast_lower=250.0,
            forecast_upper=320.0,
            selected_interventions=[],
            total_aqi_reduction=0.0,
            projected_aqi=312.0,
            health_benefit=0.0,
            enable_llm=True,
        )

        assert "Environmental Investigation Report" in summary
        assert "Vehicular Traffic Accumulation" in summary
        assert llm_error is True


@patch("requests.post")
def test_llm_summary_error_status_mock(mock_post):
    """Verifies that a bad status code (500) results in a fallback report and llm_error=True."""
    mock_response = MagicMock()
    mock_response.status_code = 500
    mock_response.text = "Internal Server Error"
    mock_post.return_value = mock_response

    with patch.dict("os.environ", {"OPENAI_API_KEY": "fake-key"}):
        summary, llm_error = generate_llm_summary(
            latitude=28.566,
            longitude=77.186,
            current_aqi=312.0,
            primary_cause="traffic",
            confidence=80.0,
            forecast_value=290.0,
            forecast_lower=250.0,
            forecast_upper=320.0,
            selected_interventions=[],
            total_aqi_reduction=0.0,
            projected_aqi=312.0,
            health_benefit=0.0,
            enable_llm=True,
        )

        assert "Environmental Investigation Report" in summary
        assert llm_error is True


@patch("requests.post")
def test_pipeline_handles_llm_timeout_gracefully(mock_post):
    """Verifies that the main pipeline runs end-to-end even when the LLM times out."""
    mock_post.side_effect = requests.exceptions.Timeout("Connection timed out")

    with patch.dict("os.environ", {"OPENAI_API_KEY": "fake-key"}):
        res = run_investigation_pipeline(
            latitude=28.566,
            longitude=77.186,
            horizon_hours=24,
            budget=5000.0,
            inspectors=5,
            max_travel_time_hours=3.0,
            enable_llm=True,
        )

        assert res.latitude == 28.566
        assert "Environmental Investigation Report" in res.summary
        assert res.llm_error is True
